### ISSUE TITLE
门户ses服务开通失败

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/SES#19]
服务开通时，所填参数如下：
集群个数：2
索引分片个数：5
索引副本个数：2
分片内存：4096M
服务名称：test_5_4096_2

后台报错如下：
2016-01-07 15:48:51,845 [http-nio-10888-exec-1] INFO  com.ai.paas.ipaas.ses.service.impl.SesSrvImpl(193) - write to zk su!
2016-01-07 15:50:14,003 [http-nio-10888-exec-5] INFO  com.ai.paas.ipaas.ses.manager.impl.SesManagerImpl(48) - create ses service begin..........
2016-01-07 15:50:14,015 [http-nio-10888-exec-5] ERROR com.ai.paas.ipaas.ses.manager.impl.SesManagerImpl(53) - create ses service error..........
com.ai.paas.ipaas.PaasException: qryAvlSesHosts error...
        at com.ai.paas.ipaas.ses.service.impl.SesSrvImpl.qryAvlSesHosts(SesSrvImpl.java:308) ~[ipaas-ses-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.ses.service.impl.SesSrvImpl.createSesService(SesSrvImpl.java:56) ~[ipaas-ses-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.ses.service.impl.SesSrvImpl$$FastClassBySpringCGLIB$$2d46c7ea.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at com.ai.paas.ipaas.ses.service.impl.SesSrvImpl$$EnhancerBySpringCGLIB$$c38c6cd8.createSesService(<generated>) ~[spring-core-4.1.6.RELEASE.jar:?]
        at com.ai.paas.ipaas.ses.manager.impl.SesManagerImpl.create(SesManagerImpl.java:49) [ipaas-ses-0.1-SNAPSHOT.jar:?]
        at com.alibaba.dubbo.common.bytecode.Wrapper21.invokeMethod(Wrapper21.java) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.common.bytecode.proxy11.create(proxy11.java) [dubbox-2.8.3.jar:2.8.3]
        at sun.reflect.GeneratedMethodAccessor253.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at com.alibaba.dubbo.rpc.protocol.rest.DubboHttpServer$RestHandler.handle(DubboHttpServer.java:86) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.remoting.http.servlet.DispatcherServlet.service(DispatcherServlet.java:64) [dubbox-2.8.3.jar:2.8.3]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_71]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[?:1.7.0_71]
        at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[?:1.7.0_71]
        at com.ai.paas.ipaas.ses.service.impl.SesSrvImpl.qryAvlSesHosts(SesSrvImpl.java:265) ~[ipaas-ses-0.1-SNAPSHOT.jar:?]
        ... 68 more

**Comment by smilence1986** [comment]
此问题是因为资源中没有足够的内存可以分配 在审核时抛出异常qryAvlSesHosts error...  门户审核时并未对此异常进行处理，比如提示资源不足 此bug需要门户组对这段代码进行调整，然而他们最近都没有时间 ，此bug可保留
